### ISSUE TITLE
Could you please provide detailed environmental information about the operation of the project?

### ISSUE THREAD

**Issue by ghost** [samlobel/RaCT_CF#2]
Hello,

I hope this message finds you well. I am currently attempting to reproduce the results presented in this repository, but I have encountered some challenges given the time elapsed since the initial publication of the repo.

To ensure the accuracy and reliability of my reproduction, could you please provide the specific details of the runtime environment that was used during the development and execution of the project? I want to know something about the version of python, whether it can be reproduced using Windows

Your assistance would be greatly appreciated as it would significantly aid in my understanding and successful implementation of the project.

Thank you in advance for your time and help.

The following is my runtime log, hope to get your help: 

```
(RaCT) E:\Code\Python\RaCT_CF\scripts>python main_vae.py
n_items: 20108
setting attribute omit_num_unseen_from_critic to False
setting attribute omit_num_seen_from_critic to False
setting attribute ac_reg_loss_scaler to 0.0
setting attribute lr_ac to 2e-06
setting attribute lr_critic to 0.0001
setting attribute lr_actor to 0.001
setting attribute evaluation_metric to NDCG
setting attribute batch_size to 500
setting attribute epochs_to_anneal_over to 50
setting attribute anneal_cap to 0.2
setting attribute input_dim to 20108
setting attribute heldout_batch to Tensor("IteratorGetNext:1", shape=(500, 20108), dtype=float32)
setting attribute batch_of_users to Tensor("IteratorGetNext:0", shape=(500, 20108), dtype=float32)
NOT OMITTING NUM SEEN
NOT OMITTING NUM UNSEEN
Always doing actor error, of course.
number of batch_norm_update_ops: 0
changed to 1e-4 from 1e-6, just so I know.
Evaluating with NDCG
changed to 1e-4 from 1e-6, just so I know.
number of BN update ops: 0
WARNING:tensorflow:VARIABLES collection name is deprecated, please use GLOBAL_VARIABLES instead; VARIABLES will be removed after 2017-03-02.
log directory: ..\logging\ml-20m\multi_vae\ac_reg_loss_scaler:0.0\actor_reg_loss_scaler:0.01\batch_size:500\batches_to_anneal_over:200000\break_early:False\epochs_to_anneal_over:50\evaluation_metric:NDCG\max_kl:0.2\min_kl:0.0\n_epochs_ac_only:0\n_epochs_pred_and_ac:0\n_epochs_pred_only:100\n_epochs_second_pred:0\omit_num_seen_from_critic:False\omit_num_unseen_from_critic:False\positive_weights:2.0\restore_trained_actor_path:None\verbose:False\version_tag:FULL_RUN_ON_OTHER_DATASETS
Traceback (most recent call last):
  File "main_vae.py", line 31, in <module>
    log_critic_training_error=False,
  File "E:\Code\Python\RaCT_CF\scripts\..\utils\training.py", line 244, in train
    summary_writer = make_summary_writer(arch_str)
  File "E:\Code\Python\RaCT_CF\scripts\..\utils\training.py", line 133, in make_summary_writer
    summary_writer = tf.summary.FileWriter(log_dir, graph=tf.get_default_graph())
  File "C:\Users\shkong\.conda\envs\RaCT\lib\site-packages\tensorflow\python\summary\writer\writer.py", line 366, in __init__
    filename_suffix)
  File "C:\Users\shkong\.conda\envs\RaCT\lib\site-packages\tensorflow\python\summary\writer\event_file_writer.py", line 67, in __init__
    gfile.MakeDirs(self._logdir)
  File "C:\Users\shkong\.conda\envs\RaCT\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 379, in recursive_create_dir
    pywrap_tensorflow.RecursivelyCreateDir(compat.as_bytes(dirname), status)
  File "C:\Users\shkong\.conda\envs\RaCT\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Failed to create a directory: ..\logging\ml-20m\multi_vae/ac_reg_loss_scaler:0.0; Invalid argument
```

**Comment by samlobel** [comment]
Hi, sorry for the slow response, I don't check my github notifications all that often.

I don't have a Windows machine to test this on, but following the Exception that you posted,  it appears the problem is that the directory name is being constructed incorrectly [here](https://github.com/samlobel/RaCT_CF/blob/master/utils/training.py#L77) (called from [here](https://github.com/samlobel/RaCT_CF/blob/master/utils/training.py#L133)).

As best I can tell it's because I use the `:` character in some of the directory names for `arch_string`, which isn't allowed on Windows. I would replace that with maybe a double-underscore for your code.

I don't have specific details on the environment sadly, but it would have been Tensorflow 1 and something like Python 3.6-3.8. Good luck! Let me know if you have more questions.
